### ISSUE TITLE
Tips for setting up a custom datasource?

### ISSUE THREAD

**Issue by mpursley** [OpenNMS/grafana#1]
@j-white  Not really an issue, but somewhat related to this fork.  :)

I've read a few posts about setting up a custom datasource, but "no documentation for that yet"...
https://github.com/grafana/grafana/issues/704
https://github.com/grafana/grafana/issues/701

I'm wondering if you have any tips, notes or examples you used to set up this custom datasource plugin?

I have some OpenTSDB-like data in hadoop (available via a rest interface) that I would like to try to get into Grafana, if possible.  I haven't done any work in js before.  I'm just trying to get the scope of work require together, so I can see if I can try it myself, or pass it off to one of our WebDevs...

Thanks!
Matt

**Comment by demianberjman** [comment]
+1

**Comment by j-white** [comment]
I had to "reverse engineer" the existing data sources in order to put my initial implementation together, but I can put together a simple example that you can use as a base.

**Comment by linar-jether** [comment]
+1

**Comment by mpursley** [comment]
@j-white  Yeah, an "example" or "template" plugin, and/or the basic setup procedures, would be better then having to reverse engineer from the existing data sources again.  Thanks!  :)

**Comment by j-white** [comment]
Grafana 3.x makes writing custom data source easier.

They have a sample datasource project here:
https://github.com/grafana/simple-json-datasource

And documentation is available here: https://github.com/grafana/grafana/blob/master/docs/sources/plugins/datasources.md
