### ISSUE TITLE
Unable to use friendly names in Templating

### ISSUE THREAD

**Issue by papersackpuppet** [OpenNMS/grafana#2]
Hi all,

I am trying to set up templating in the newest version of the plugin (1.1.0) on OpenNMS 16.0.3.

When I add the attributes to a graph manually and select a node from the node browser, it inputs the foreign ID for the node instead of a friendly name.

![Selecting a server](http://i.imgur.com/GExacNH.png)
![Servers use foreign ID](http://i.imgur.com/0wvj6RD.png)

Unfortunately, it doesn't seem like this field will accept friendly names. Consequently, using friendly names in the template variable doesn't work either. Adding the foreign IDs to the template variable works as expected.

Is there any way to get the Grafana plugin to utilize the node names like on this blog post instead?

http://www.jessewhite.ca/opennms/grafana/2015/10/31/opennms-grafana-datasource.html

**Comment by j-white** [comment]
Friendly names are not supported in the 'Node' field, only the node id and foreign source / foreign id can be used here.

The referenced blog post uses a template parameter for the foreign id. In the given example, the node names just happen to be the same as the foreign ids.
